### ISSUE TITLE
Sử dụng MindNote để vẽ lại cấu trúc ứng dụng YouTube

### ISSUE THREAD

**Issue by TechMaster** [TechMaster/YouTubeClone#1]
Gửi lại càng nhanh càng tốt

**Comment by nguyenphuckhanh91** [comment]
Gửi anh file mindnote cấu trúc ứng dụng Youtube!
[YoutubeClone App.zip](https://github.com/TechMaster/YouTubeClone/files/969380/YoutubeClone.App.zip)
